name: Docker Image CI

on:
  push:
    branches: [ main ]
    tags:
      - v2
      - v1.*
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: | 
        docker version
        # 登录阿里云镜像仓库
        docker login --username=${{ secrets.DOCKER_HUB_USERNAME }} --password=${{ secrets.DOCKER_HUB_PASSWORD }} hub.docker.com
        # 使用Dockerfile构建镜像
        docker build . --file Dockerfile --tag hub.docker.com/aileen5150/hanlp-jupyterlab
        # 推送镜像到镜像仓库
        docker push hub.docker.com/aileen5150/hanlp-jupyterlab
